package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjcczzTdly implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.YLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double yld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GMLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gmld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.SLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.QTLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double qtld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.LDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ldmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.LDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ldfqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gfgcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ZFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double zfgcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.DFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double dfgcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.CDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double cdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.CDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double cdfqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ST1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double st1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ST2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double st2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ST3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double st3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ST4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double st4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HD1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HD2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HD3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HD4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GDQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gdqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HQ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.HP
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double hp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.SKKT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double skkt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.TD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double td;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.SYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double symj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.SYSDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sysdfqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.CZYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double czyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.NCJMYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ncjmyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GJYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gjyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.JZYDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double jzydmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.JZYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double jzydfqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.SD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.GB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double gb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.YJD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double yjd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.ZZD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double zzd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.LTD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ltd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.LY
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.QT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double qt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.WLYTDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double wlytdmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.WLYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double wlydfqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjcczz_tdly.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjcczz_tdly
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ID
     *
     * @return the value of t_hjcczz_tdly.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ID
     *
     * @param id the value for t_hjcczz_tdly.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.XZQMC
     *
     * @return the value of t_hjcczz_tdly.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.XZQMC
     *
     * @param xzqmc the value for t_hjcczz_tdly.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.XZQDM
     *
     * @return the value of t_hjcczz_tdly.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.XZQDM
     *
     * @param xzqdm the value for t_hjcczz_tdly.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.YLD
     *
     * @return the value of t_hjcczz_tdly.YLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getYld() {
        return yld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.YLD
     *
     * @param yld the value for t_hjcczz_tdly.YLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setYld(Double yld) {
        this.yld = yld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GMLD
     *
     * @return the value of t_hjcczz_tdly.GMLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGmld() {
        return gmld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GMLD
     *
     * @param gmld the value for t_hjcczz_tdly.GMLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGmld(Double gmld) {
        this.gmld = gmld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.SLD
     *
     * @return the value of t_hjcczz_tdly.SLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSld() {
        return sld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.SLD
     *
     * @param sld the value for t_hjcczz_tdly.SLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSld(Double sld) {
        this.sld = sld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.QTLD
     *
     * @return the value of t_hjcczz_tdly.QTLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getQtld() {
        return qtld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.QTLD
     *
     * @param qtld the value for t_hjcczz_tdly.QTLD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setQtld(Double qtld) {
        this.qtld = qtld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.LDMJ
     *
     * @return the value of t_hjcczz_tdly.LDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getLdmj() {
        return ldmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.LDMJ
     *
     * @param ldmj the value for t_hjcczz_tdly.LDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setLdmj(Double ldmj) {
        this.ldmj = ldmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.LDFQZ
     *
     * @return the value of t_hjcczz_tdly.LDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getLdfqz() {
        return ldfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.LDFQZ
     *
     * @param ldfqz the value for t_hjcczz_tdly.LDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setLdfqz(Double ldfqz) {
        this.ldfqz = ldfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GFGCD
     *
     * @return the value of t_hjcczz_tdly.GFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGfgcd() {
        return gfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GFGCD
     *
     * @param gfgcd the value for t_hjcczz_tdly.GFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGfgcd(Double gfgcd) {
        this.gfgcd = gfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ZFGCD
     *
     * @return the value of t_hjcczz_tdly.ZFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getZfgcd() {
        return zfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ZFGCD
     *
     * @param zfgcd the value for t_hjcczz_tdly.ZFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setZfgcd(Double zfgcd) {
        this.zfgcd = zfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.DFGCD
     *
     * @return the value of t_hjcczz_tdly.DFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getDfgcd() {
        return dfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.DFGCD
     *
     * @param dfgcd the value for t_hjcczz_tdly.DFGCD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setDfgcd(Double dfgcd) {
        this.dfgcd = dfgcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.CDMJ
     *
     * @return the value of t_hjcczz_tdly.CDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getCdmj() {
        return cdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.CDMJ
     *
     * @param cdmj the value for t_hjcczz_tdly.CDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setCdmj(Double cdmj) {
        this.cdmj = cdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.CDFQZ
     *
     * @return the value of t_hjcczz_tdly.CDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getCdfqz() {
        return cdfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.CDFQZ
     *
     * @param cdfqz the value for t_hjcczz_tdly.CDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setCdfqz(Double cdfqz) {
        this.cdfqz = cdfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ST1
     *
     * @return the value of t_hjcczz_tdly.ST1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSt1() {
        return st1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ST1
     *
     * @param st1 the value for t_hjcczz_tdly.ST1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSt1(Double st1) {
        this.st1 = st1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ST2
     *
     * @return the value of t_hjcczz_tdly.ST2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSt2() {
        return st2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ST2
     *
     * @param st2 the value for t_hjcczz_tdly.ST2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSt2(Double st2) {
        this.st2 = st2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ST3
     *
     * @return the value of t_hjcczz_tdly.ST3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSt3() {
        return st3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ST3
     *
     * @param st3 the value for t_hjcczz_tdly.ST3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSt3(Double st3) {
        this.st3 = st3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ST4
     *
     * @return the value of t_hjcczz_tdly.ST4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSt4() {
        return st4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ST4
     *
     * @param st4 the value for t_hjcczz_tdly.ST4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSt4(Double st4) {
        this.st4 = st4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HD1
     *
     * @return the value of t_hjcczz_tdly.HD1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHd1() {
        return hd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HD1
     *
     * @param hd1 the value for t_hjcczz_tdly.HD1
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHd1(Double hd1) {
        this.hd1 = hd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HD2
     *
     * @return the value of t_hjcczz_tdly.HD2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHd2() {
        return hd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HD2
     *
     * @param hd2 the value for t_hjcczz_tdly.HD2
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHd2(Double hd2) {
        this.hd2 = hd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HD3
     *
     * @return the value of t_hjcczz_tdly.HD3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHd3() {
        return hd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HD3
     *
     * @param hd3 the value for t_hjcczz_tdly.HD3
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHd3(Double hd3) {
        this.hd3 = hd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HD4
     *
     * @return the value of t_hjcczz_tdly.HD4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHd4() {
        return hd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HD4
     *
     * @param hd4 the value for t_hjcczz_tdly.HD4
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHd4(Double hd4) {
        this.hd4 = hd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GDMJ
     *
     * @return the value of t_hjcczz_tdly.GDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGdmj() {
        return gdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GDMJ
     *
     * @param gdmj the value for t_hjcczz_tdly.GDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGdmj(Double gdmj) {
        this.gdmj = gdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GDQZ
     *
     * @return the value of t_hjcczz_tdly.GDQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGdqz() {
        return gdqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GDQZ
     *
     * @param gdqz the value for t_hjcczz_tdly.GDQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGdqz(Double gdqz) {
        this.gdqz = gdqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HQ
     *
     * @return the value of t_hjcczz_tdly.HQ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHq() {
        return hq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HQ
     *
     * @param hq the value for t_hjcczz_tdly.HQ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHq(Double hq) {
        this.hq = hq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.HP
     *
     * @return the value of t_hjcczz_tdly.HP
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.HP
     *
     * @param hp the value for t_hjcczz_tdly.HP
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setHp(Double hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.SKKT
     *
     * @return the value of t_hjcczz_tdly.SKKT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSkkt() {
        return skkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.SKKT
     *
     * @param skkt the value for t_hjcczz_tdly.SKKT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSkkt(Double skkt) {
        this.skkt = skkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.TD
     *
     * @return the value of t_hjcczz_tdly.TD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getTd() {
        return td;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.TD
     *
     * @param td the value for t_hjcczz_tdly.TD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setTd(Double td) {
        this.td = td;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.SYMJ
     *
     * @return the value of t_hjcczz_tdly.SYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSymj() {
        return symj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.SYMJ
     *
     * @param symj the value for t_hjcczz_tdly.SYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSymj(Double symj) {
        this.symj = symj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.SYSDFQZ
     *
     * @return the value of t_hjcczz_tdly.SYSDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSysdfqz() {
        return sysdfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.SYSDFQZ
     *
     * @param sysdfqz the value for t_hjcczz_tdly.SYSDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSysdfqz(Double sysdfqz) {
        this.sysdfqz = sysdfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.CZYD
     *
     * @return the value of t_hjcczz_tdly.CZYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getCzyd() {
        return czyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.CZYD
     *
     * @param czyd the value for t_hjcczz_tdly.CZYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setCzyd(Double czyd) {
        this.czyd = czyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.NCJMYD
     *
     * @return the value of t_hjcczz_tdly.NCJMYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getNcjmyd() {
        return ncjmyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.NCJMYD
     *
     * @param ncjmyd the value for t_hjcczz_tdly.NCJMYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setNcjmyd(Double ncjmyd) {
        this.ncjmyd = ncjmyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GJYD
     *
     * @return the value of t_hjcczz_tdly.GJYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGjyd() {
        return gjyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GJYD
     *
     * @param gjyd the value for t_hjcczz_tdly.GJYD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGjyd(Double gjyd) {
        this.gjyd = gjyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.JZYDMJ
     *
     * @return the value of t_hjcczz_tdly.JZYDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getJzydmj() {
        return jzydmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.JZYDMJ
     *
     * @param jzydmj the value for t_hjcczz_tdly.JZYDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setJzydmj(Double jzydmj) {
        this.jzydmj = jzydmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.JZYDFQZ
     *
     * @return the value of t_hjcczz_tdly.JZYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getJzydfqz() {
        return jzydfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.JZYDFQZ
     *
     * @param jzydfqz the value for t_hjcczz_tdly.JZYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setJzydfqz(Double jzydfqz) {
        this.jzydfqz = jzydfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.SD
     *
     * @return the value of t_hjcczz_tdly.SD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSd() {
        return sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.SD
     *
     * @param sd the value for t_hjcczz_tdly.SD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSd(Double sd) {
        this.sd = sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.GB
     *
     * @return the value of t_hjcczz_tdly.GB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getGb() {
        return gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.GB
     *
     * @param gb the value for t_hjcczz_tdly.GB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGb(Double gb) {
        this.gb = gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.YJD
     *
     * @return the value of t_hjcczz_tdly.YJD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getYjd() {
        return yjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.YJD
     *
     * @param yjd the value for t_hjcczz_tdly.YJD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setYjd(Double yjd) {
        this.yjd = yjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.ZZD
     *
     * @return the value of t_hjcczz_tdly.ZZD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getZzd() {
        return zzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.ZZD
     *
     * @param zzd the value for t_hjcczz_tdly.ZZD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setZzd(Double zzd) {
        this.zzd = zzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.LTD
     *
     * @return the value of t_hjcczz_tdly.LTD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getLtd() {
        return ltd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.LTD
     *
     * @param ltd the value for t_hjcczz_tdly.LTD
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setLtd(Double ltd) {
        this.ltd = ltd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.LY
     *
     * @return the value of t_hjcczz_tdly.LY
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getLy() {
        return ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.LY
     *
     * @param ly the value for t_hjcczz_tdly.LY
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setLy(Double ly) {
        this.ly = ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.QT
     *
     * @return the value of t_hjcczz_tdly.QT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.QT
     *
     * @param qt the value for t_hjcczz_tdly.QT
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setQt(Double qt) {
        this.qt = qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.WLYTDMJ
     *
     * @return the value of t_hjcczz_tdly.WLYTDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getWlytdmj() {
        return wlytdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.WLYTDMJ
     *
     * @param wlytdmj the value for t_hjcczz_tdly.WLYTDMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setWlytdmj(Double wlytdmj) {
        this.wlytdmj = wlytdmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.WLYDFQZ
     *
     * @return the value of t_hjcczz_tdly.WLYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getWlydfqz() {
        return wlydfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.WLYDFQZ
     *
     * @param wlydfqz the value for t_hjcczz_tdly.WLYDFQZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setWlydfqz(Double wlydfqz) {
        this.wlydfqz = wlydfqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjcczz_tdly.MJ
     *
     * @return the value of t_hjcczz_tdly.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjcczz_tdly.MJ
     *
     * @param mj the value for t_hjcczz_tdly.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }
}