package com.fiprs.springbootdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class THjjczzHjxzzsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public THjjczzHjxzzsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNull() {
            addCriterion("XZQMC is null");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNotNull() {
            addCriterion("XZQMC is not null");
            return (Criteria) this;
        }

        public Criteria andXzqmcEqualTo(String value) {
            addCriterion("XZQMC =", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotEqualTo(String value) {
            addCriterion("XZQMC <>", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThan(String value) {
            addCriterion("XZQMC >", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThanOrEqualTo(String value) {
            addCriterion("XZQMC >=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThan(String value) {
            addCriterion("XZQMC <", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThanOrEqualTo(String value) {
            addCriterion("XZQMC <=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLike(String value) {
            addCriterion("XZQMC like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotLike(String value) {
            addCriterion("XZQMC not like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcIn(List<String> values) {
            addCriterion("XZQMC in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotIn(List<String> values) {
            addCriterion("XZQMC not in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcBetween(String value1, String value2) {
            addCriterion("XZQMC between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotBetween(String value1, String value2) {
            addCriterion("XZQMC not between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNull() {
            addCriterion("XZQDM is null");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNotNull() {
            addCriterion("XZQDM is not null");
            return (Criteria) this;
        }

        public Criteria andXzqdmEqualTo(String value) {
            addCriterion("XZQDM =", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotEqualTo(String value) {
            addCriterion("XZQDM <>", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThan(String value) {
            addCriterion("XZQDM >", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThanOrEqualTo(String value) {
            addCriterion("XZQDM >=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThan(String value) {
            addCriterion("XZQDM <", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThanOrEqualTo(String value) {
            addCriterion("XZQDM <=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLike(String value) {
            addCriterion("XZQDM like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotLike(String value) {
            addCriterion("XZQDM not like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmIn(List<String> values) {
            addCriterion("XZQDM in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotIn(List<String> values) {
            addCriterion("XZQDM not in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmBetween(String value1, String value2) {
            addCriterion("XZQDM between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotBetween(String value1, String value2) {
            addCriterion("XZQDM not between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andTdhjsjIsNull() {
            addCriterion("TDHJSJ is null");
            return (Criteria) this;
        }

        public Criteria andTdhjsjIsNotNull() {
            addCriterion("TDHJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andTdhjsjEqualTo(Integer value) {
            addCriterion("TDHJSJ =", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjNotEqualTo(Integer value) {
            addCriterion("TDHJSJ <>", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjGreaterThan(Integer value) {
            addCriterion("TDHJSJ >", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("TDHJSJ >=", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjLessThan(Integer value) {
            addCriterion("TDHJSJ <", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjLessThanOrEqualTo(Integer value) {
            addCriterion("TDHJSJ <=", value, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjIn(List<Integer> values) {
            addCriterion("TDHJSJ in", values, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjNotIn(List<Integer> values) {
            addCriterion("TDHJSJ not in", values, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjBetween(Integer value1, Integer value2) {
            addCriterion("TDHJSJ between", value1, value2, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andTdhjsjNotBetween(Integer value1, Integer value2) {
            addCriterion("TDHJSJ not between", value1, value2, "tdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjIsNull() {
            addCriterion("ZDHJSJ is null");
            return (Criteria) this;
        }

        public Criteria andZdhjsjIsNotNull() {
            addCriterion("ZDHJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZdhjsjEqualTo(Integer value) {
            addCriterion("ZDHJSJ =", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjNotEqualTo(Integer value) {
            addCriterion("ZDHJSJ <>", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjGreaterThan(Integer value) {
            addCriterion("ZDHJSJ >", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("ZDHJSJ >=", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjLessThan(Integer value) {
            addCriterion("ZDHJSJ <", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjLessThanOrEqualTo(Integer value) {
            addCriterion("ZDHJSJ <=", value, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjIn(List<Integer> values) {
            addCriterion("ZDHJSJ in", values, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjNotIn(List<Integer> values) {
            addCriterion("ZDHJSJ not in", values, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjBetween(Integer value1, Integer value2) {
            addCriterion("ZDHJSJ between", value1, value2, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andZdhjsjNotBetween(Integer value1, Integer value2) {
            addCriterion("ZDHJSJ not between", value1, value2, "zdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjIsNull() {
            addCriterion("JDHJSJ is null");
            return (Criteria) this;
        }

        public Criteria andJdhjsjIsNotNull() {
            addCriterion("JDHJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJdhjsjEqualTo(Integer value) {
            addCriterion("JDHJSJ =", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjNotEqualTo(Integer value) {
            addCriterion("JDHJSJ <>", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjGreaterThan(Integer value) {
            addCriterion("JDHJSJ >", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("JDHJSJ >=", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjLessThan(Integer value) {
            addCriterion("JDHJSJ <", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjLessThanOrEqualTo(Integer value) {
            addCriterion("JDHJSJ <=", value, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjIn(List<Integer> values) {
            addCriterion("JDHJSJ in", values, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjNotIn(List<Integer> values) {
            addCriterion("JDHJSJ not in", values, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjBetween(Integer value1, Integer value2) {
            addCriterion("JDHJSJ between", value1, value2, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andJdhjsjNotBetween(Integer value1, Integer value2) {
            addCriterion("JDHJSJ not between", value1, value2, "jdhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjIsNull() {
            addCriterion("YBHJSJ is null");
            return (Criteria) this;
        }

        public Criteria andYbhjsjIsNotNull() {
            addCriterion("YBHJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andYbhjsjEqualTo(Integer value) {
            addCriterion("YBHJSJ =", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjNotEqualTo(Integer value) {
            addCriterion("YBHJSJ <>", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjGreaterThan(Integer value) {
            addCriterion("YBHJSJ >", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjGreaterThanOrEqualTo(Integer value) {
            addCriterion("YBHJSJ >=", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjLessThan(Integer value) {
            addCriterion("YBHJSJ <", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjLessThanOrEqualTo(Integer value) {
            addCriterion("YBHJSJ <=", value, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjIn(List<Integer> values) {
            addCriterion("YBHJSJ in", values, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjNotIn(List<Integer> values) {
            addCriterion("YBHJSJ not in", values, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjBetween(Integer value1, Integer value2) {
            addCriterion("YBHJSJ between", value1, value2, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andYbhjsjNotBetween(Integer value1, Integer value2) {
            addCriterion("YBHJSJ not between", value1, value2, "ybhjsj");
            return (Criteria) this;
        }

        public Criteria andHjwrIsNull() {
            addCriterion("HJWR is null");
            return (Criteria) this;
        }

        public Criteria andHjwrIsNotNull() {
            addCriterion("HJWR is not null");
            return (Criteria) this;
        }

        public Criteria andHjwrEqualTo(Integer value) {
            addCriterion("HJWR =", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrNotEqualTo(Integer value) {
            addCriterion("HJWR <>", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrGreaterThan(Integer value) {
            addCriterion("HJWR >", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrGreaterThanOrEqualTo(Integer value) {
            addCriterion("HJWR >=", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrLessThan(Integer value) {
            addCriterion("HJWR <", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrLessThanOrEqualTo(Integer value) {
            addCriterion("HJWR <=", value, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrIn(List<Integer> values) {
            addCriterion("HJWR in", values, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrNotIn(List<Integer> values) {
            addCriterion("HJWR not in", values, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrBetween(Integer value1, Integer value2) {
            addCriterion("HJWR between", value1, value2, "hjwr");
            return (Criteria) this;
        }

        public Criteria andHjwrNotBetween(Integer value1, Integer value2) {
            addCriterion("HJWR not between", value1, value2, "hjwr");
            return (Criteria) this;
        }

        public Criteria andStphIsNull() {
            addCriterion("STPH is null");
            return (Criteria) this;
        }

        public Criteria andStphIsNotNull() {
            addCriterion("STPH is not null");
            return (Criteria) this;
        }

        public Criteria andStphEqualTo(Integer value) {
            addCriterion("STPH =", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphNotEqualTo(Integer value) {
            addCriterion("STPH <>", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphGreaterThan(Integer value) {
            addCriterion("STPH >", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphGreaterThanOrEqualTo(Integer value) {
            addCriterion("STPH >=", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphLessThan(Integer value) {
            addCriterion("STPH <", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphLessThanOrEqualTo(Integer value) {
            addCriterion("STPH <=", value, "stph");
            return (Criteria) this;
        }

        public Criteria andStphIn(List<Integer> values) {
            addCriterion("STPH in", values, "stph");
            return (Criteria) this;
        }

        public Criteria andStphNotIn(List<Integer> values) {
            addCriterion("STPH not in", values, "stph");
            return (Criteria) this;
        }

        public Criteria andStphBetween(Integer value1, Integer value2) {
            addCriterion("STPH between", value1, value2, "stph");
            return (Criteria) this;
        }

        public Criteria andStphNotBetween(Integer value1, Integer value2) {
            addCriterion("STPH not between", value1, value2, "stph");
            return (Criteria) this;
        }

        public Criteria andSthjwfajIsNull() {
            addCriterion("STHJWFAJ is null");
            return (Criteria) this;
        }

        public Criteria andSthjwfajIsNotNull() {
            addCriterion("STHJWFAJ is not null");
            return (Criteria) this;
        }

        public Criteria andSthjwfajEqualTo(Integer value) {
            addCriterion("STHJWFAJ =", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajNotEqualTo(Integer value) {
            addCriterion("STHJWFAJ <>", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajGreaterThan(Integer value) {
            addCriterion("STHJWFAJ >", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajGreaterThanOrEqualTo(Integer value) {
            addCriterion("STHJWFAJ >=", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajLessThan(Integer value) {
            addCriterion("STHJWFAJ <", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajLessThanOrEqualTo(Integer value) {
            addCriterion("STHJWFAJ <=", value, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajIn(List<Integer> values) {
            addCriterion("STHJWFAJ in", values, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajNotIn(List<Integer> values) {
            addCriterion("STHJWFAJ not in", values, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajBetween(Integer value1, Integer value2) {
            addCriterion("STHJWFAJ between", value1, value2, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andSthjwfajNotBetween(Integer value1, Integer value2) {
            addCriterion("STHJWFAJ not between", value1, value2, "sthjwfaj");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwIsNull() {
            addCriterion("BNRQYXPFW is null");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwIsNotNull() {
            addCriterion("BNRQYXPFW is not null");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwEqualTo(Integer value) {
            addCriterion("BNRQYXPFW =", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwNotEqualTo(Integer value) {
            addCriterion("BNRQYXPFW <>", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwGreaterThan(Integer value) {
            addCriterion("BNRQYXPFW >", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwGreaterThanOrEqualTo(Integer value) {
            addCriterion("BNRQYXPFW >=", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwLessThan(Integer value) {
            addCriterion("BNRQYXPFW <", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwLessThanOrEqualTo(Integer value) {
            addCriterion("BNRQYXPFW <=", value, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwIn(List<Integer> values) {
            addCriterion("BNRQYXPFW in", values, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwNotIn(List<Integer> values) {
            addCriterion("BNRQYXPFW not in", values, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwBetween(Integer value1, Integer value2) {
            addCriterion("BNRQYXPFW between", value1, value2, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andBnrqyxpfwNotBetween(Integer value1, Integer value2) {
            addCriterion("BNRQYXPFW not between", value1, value2, "bnrqyxpfw");
            return (Criteria) this;
        }

        public Criteria andHjxzzsIsNull() {
            addCriterion("HJXZZS is null");
            return (Criteria) this;
        }

        public Criteria andHjxzzsIsNotNull() {
            addCriterion("HJXZZS is not null");
            return (Criteria) this;
        }

        public Criteria andHjxzzsEqualTo(Integer value) {
            addCriterion("HJXZZS =", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsNotEqualTo(Integer value) {
            addCriterion("HJXZZS <>", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsGreaterThan(Integer value) {
            addCriterion("HJXZZS >", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsGreaterThanOrEqualTo(Integer value) {
            addCriterion("HJXZZS >=", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsLessThan(Integer value) {
            addCriterion("HJXZZS <", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsLessThanOrEqualTo(Integer value) {
            addCriterion("HJXZZS <=", value, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsIn(List<Integer> values) {
            addCriterion("HJXZZS in", values, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsNotIn(List<Integer> values) {
            addCriterion("HJXZZS not in", values, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsBetween(Integer value1, Integer value2) {
            addCriterion("HJXZZS between", value1, value2, "hjxzzs");
            return (Criteria) this;
        }

        public Criteria andHjxzzsNotBetween(Integer value1, Integer value2) {
            addCriterion("HJXZZS not between", value1, value2, "hjxzzs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_hjxzzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}