package com.fiprs.springbootdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class THjjczzWrfhzsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public THjjczzWrfhzsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNull() {
            addCriterion("XZQMC is null");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNotNull() {
            addCriterion("XZQMC is not null");
            return (Criteria) this;
        }

        public Criteria andXzqmcEqualTo(String value) {
            addCriterion("XZQMC =", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotEqualTo(String value) {
            addCriterion("XZQMC <>", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThan(String value) {
            addCriterion("XZQMC >", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThanOrEqualTo(String value) {
            addCriterion("XZQMC >=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThan(String value) {
            addCriterion("XZQMC <", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThanOrEqualTo(String value) {
            addCriterion("XZQMC <=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLike(String value) {
            addCriterion("XZQMC like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotLike(String value) {
            addCriterion("XZQMC not like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcIn(List<String> values) {
            addCriterion("XZQMC in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotIn(List<String> values) {
            addCriterion("XZQMC not in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcBetween(String value1, String value2) {
            addCriterion("XZQMC between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotBetween(String value1, String value2) {
            addCriterion("XZQMC not between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNull() {
            addCriterion("XZQDM is null");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNotNull() {
            addCriterion("XZQDM is not null");
            return (Criteria) this;
        }

        public Criteria andXzqdmEqualTo(String value) {
            addCriterion("XZQDM =", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotEqualTo(String value) {
            addCriterion("XZQDM <>", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThan(String value) {
            addCriterion("XZQDM >", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThanOrEqualTo(String value) {
            addCriterion("XZQDM >=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThan(String value) {
            addCriterion("XZQDM <", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThanOrEqualTo(String value) {
            addCriterion("XZQDM <=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLike(String value) {
            addCriterion("XZQDM like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotLike(String value) {
            addCriterion("XZQDM not like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmIn(List<String> values) {
            addCriterion("XZQDM in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotIn(List<String> values) {
            addCriterion("XZQDM not in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmBetween(String value1, String value2) {
            addCriterion("XZQDM between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotBetween(String value1, String value2) {
            addCriterion("XZQDM not between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andMjIsNull() {
            addCriterion("MJ is null");
            return (Criteria) this;
        }

        public Criteria andMjIsNotNull() {
            addCriterion("MJ is not null");
            return (Criteria) this;
        }

        public Criteria andMjEqualTo(Double value) {
            addCriterion("MJ =", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotEqualTo(Double value) {
            addCriterion("MJ <>", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThan(Double value) {
            addCriterion("MJ >", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThanOrEqualTo(Double value) {
            addCriterion("MJ >=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThan(Double value) {
            addCriterion("MJ <", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThanOrEqualTo(Double value) {
            addCriterion("MJ <=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjIn(List<Double> values) {
            addCriterion("MJ in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotIn(List<Double> values) {
            addCriterion("MJ not in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjBetween(Double value1, Double value2) {
            addCriterion("MJ between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotBetween(Double value1, Double value2) {
            addCriterion("MJ not between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andNjslIsNull() {
            addCriterion("NJSL is null");
            return (Criteria) this;
        }

        public Criteria andNjslIsNotNull() {
            addCriterion("NJSL is not null");
            return (Criteria) this;
        }

        public Criteria andNjslEqualTo(Double value) {
            addCriterion("NJSL =", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslNotEqualTo(Double value) {
            addCriterion("NJSL <>", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslGreaterThan(Double value) {
            addCriterion("NJSL >", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslGreaterThanOrEqualTo(Double value) {
            addCriterion("NJSL >=", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslLessThan(Double value) {
            addCriterion("NJSL <", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslLessThanOrEqualTo(Double value) {
            addCriterion("NJSL <=", value, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslIn(List<Double> values) {
            addCriterion("NJSL in", values, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslNotIn(List<Double> values) {
            addCriterion("NJSL not in", values, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslBetween(Double value1, Double value2) {
            addCriterion("NJSL between", value1, value2, "njsl");
            return (Criteria) this;
        }

        public Criteria andNjslNotBetween(Double value1, Double value2) {
            addCriterion("NJSL not between", value1, value2, "njsl");
            return (Criteria) this;
        }

        public Criteria andCodpflIsNull() {
            addCriterion("CODPFL is null");
            return (Criteria) this;
        }

        public Criteria andCodpflIsNotNull() {
            addCriterion("CODPFL is not null");
            return (Criteria) this;
        }

        public Criteria andCodpflEqualTo(Double value) {
            addCriterion("CODPFL =", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflNotEqualTo(Double value) {
            addCriterion("CODPFL <>", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflGreaterThan(Double value) {
            addCriterion("CODPFL >", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflGreaterThanOrEqualTo(Double value) {
            addCriterion("CODPFL >=", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflLessThan(Double value) {
            addCriterion("CODPFL <", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflLessThanOrEqualTo(Double value) {
            addCriterion("CODPFL <=", value, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflIn(List<Double> values) {
            addCriterion("CODPFL in", values, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflNotIn(List<Double> values) {
            addCriterion("CODPFL not in", values, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflBetween(Double value1, Double value2) {
            addCriterion("CODPFL between", value1, value2, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodpflNotBetween(Double value1, Double value2) {
            addCriterion("CODPFL not between", value1, value2, "codpfl");
            return (Criteria) this;
        }

        public Criteria andCodxsIsNull() {
            addCriterion("CODXS is null");
            return (Criteria) this;
        }

        public Criteria andCodxsIsNotNull() {
            addCriterion("CODXS is not null");
            return (Criteria) this;
        }

        public Criteria andCodxsEqualTo(Double value) {
            addCriterion("CODXS =", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsNotEqualTo(Double value) {
            addCriterion("CODXS <>", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsGreaterThan(Double value) {
            addCriterion("CODXS >", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsGreaterThanOrEqualTo(Double value) {
            addCriterion("CODXS >=", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsLessThan(Double value) {
            addCriterion("CODXS <", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsLessThanOrEqualTo(Double value) {
            addCriterion("CODXS <=", value, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsIn(List<Double> values) {
            addCriterion("CODXS in", values, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsNotIn(List<Double> values) {
            addCriterion("CODXS not in", values, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsBetween(Double value1, Double value2) {
            addCriterion("CODXS between", value1, value2, "codxs");
            return (Criteria) this;
        }

        public Criteria andCodxsNotBetween(Double value1, Double value2) {
            addCriterion("CODXS not between", value1, value2, "codxs");
            return (Criteria) this;
        }

        public Criteria andAdpflIsNull() {
            addCriterion("ADPFL is null");
            return (Criteria) this;
        }

        public Criteria andAdpflIsNotNull() {
            addCriterion("ADPFL is not null");
            return (Criteria) this;
        }

        public Criteria andAdpflEqualTo(Double value) {
            addCriterion("ADPFL =", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflNotEqualTo(Double value) {
            addCriterion("ADPFL <>", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflGreaterThan(Double value) {
            addCriterion("ADPFL >", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflGreaterThanOrEqualTo(Double value) {
            addCriterion("ADPFL >=", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflLessThan(Double value) {
            addCriterion("ADPFL <", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflLessThanOrEqualTo(Double value) {
            addCriterion("ADPFL <=", value, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflIn(List<Double> values) {
            addCriterion("ADPFL in", values, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflNotIn(List<Double> values) {
            addCriterion("ADPFL not in", values, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflBetween(Double value1, Double value2) {
            addCriterion("ADPFL between", value1, value2, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdpflNotBetween(Double value1, Double value2) {
            addCriterion("ADPFL not between", value1, value2, "adpfl");
            return (Criteria) this;
        }

        public Criteria andAdxsIsNull() {
            addCriterion("ADXS is null");
            return (Criteria) this;
        }

        public Criteria andAdxsIsNotNull() {
            addCriterion("ADXS is not null");
            return (Criteria) this;
        }

        public Criteria andAdxsEqualTo(Double value) {
            addCriterion("ADXS =", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsNotEqualTo(Double value) {
            addCriterion("ADXS <>", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsGreaterThan(Double value) {
            addCriterion("ADXS >", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsGreaterThanOrEqualTo(Double value) {
            addCriterion("ADXS >=", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsLessThan(Double value) {
            addCriterion("ADXS <", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsLessThanOrEqualTo(Double value) {
            addCriterion("ADXS <=", value, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsIn(List<Double> values) {
            addCriterion("ADXS in", values, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsNotIn(List<Double> values) {
            addCriterion("ADXS not in", values, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsBetween(Double value1, Double value2) {
            addCriterion("ADXS between", value1, value2, "adxs");
            return (Criteria) this;
        }

        public Criteria andAdxsNotBetween(Double value1, Double value2) {
            addCriterion("ADXS not between", value1, value2, "adxs");
            return (Criteria) this;
        }

        public Criteria andEyhlpflIsNull() {
            addCriterion("EYHLPFL is null");
            return (Criteria) this;
        }

        public Criteria andEyhlpflIsNotNull() {
            addCriterion("EYHLPFL is not null");
            return (Criteria) this;
        }

        public Criteria andEyhlpflEqualTo(Double value) {
            addCriterion("EYHLPFL =", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflNotEqualTo(Double value) {
            addCriterion("EYHLPFL <>", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflGreaterThan(Double value) {
            addCriterion("EYHLPFL >", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflGreaterThanOrEqualTo(Double value) {
            addCriterion("EYHLPFL >=", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflLessThan(Double value) {
            addCriterion("EYHLPFL <", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflLessThanOrEqualTo(Double value) {
            addCriterion("EYHLPFL <=", value, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflIn(List<Double> values) {
            addCriterion("EYHLPFL in", values, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflNotIn(List<Double> values) {
            addCriterion("EYHLPFL not in", values, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflBetween(Double value1, Double value2) {
            addCriterion("EYHLPFL between", value1, value2, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlpflNotBetween(Double value1, Double value2) {
            addCriterion("EYHLPFL not between", value1, value2, "eyhlpfl");
            return (Criteria) this;
        }

        public Criteria andEyhlxsIsNull() {
            addCriterion("EYHLXS is null");
            return (Criteria) this;
        }

        public Criteria andEyhlxsIsNotNull() {
            addCriterion("EYHLXS is not null");
            return (Criteria) this;
        }

        public Criteria andEyhlxsEqualTo(Double value) {
            addCriterion("EYHLXS =", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsNotEqualTo(Double value) {
            addCriterion("EYHLXS <>", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsGreaterThan(Double value) {
            addCriterion("EYHLXS >", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsGreaterThanOrEqualTo(Double value) {
            addCriterion("EYHLXS >=", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsLessThan(Double value) {
            addCriterion("EYHLXS <", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsLessThanOrEqualTo(Double value) {
            addCriterion("EYHLXS <=", value, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsIn(List<Double> values) {
            addCriterion("EYHLXS in", values, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsNotIn(List<Double> values) {
            addCriterion("EYHLXS not in", values, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsBetween(Double value1, Double value2) {
            addCriterion("EYHLXS between", value1, value2, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andEyhlxsNotBetween(Double value1, Double value2) {
            addCriterion("EYHLXS not between", value1, value2, "eyhlxs");
            return (Criteria) this;
        }

        public Criteria andYfcpflIsNull() {
            addCriterion("YFCPFL is null");
            return (Criteria) this;
        }

        public Criteria andYfcpflIsNotNull() {
            addCriterion("YFCPFL is not null");
            return (Criteria) this;
        }

        public Criteria andYfcpflEqualTo(Double value) {
            addCriterion("YFCPFL =", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflNotEqualTo(Double value) {
            addCriterion("YFCPFL <>", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflGreaterThan(Double value) {
            addCriterion("YFCPFL >", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflGreaterThanOrEqualTo(Double value) {
            addCriterion("YFCPFL >=", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflLessThan(Double value) {
            addCriterion("YFCPFL <", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflLessThanOrEqualTo(Double value) {
            addCriterion("YFCPFL <=", value, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflIn(List<Double> values) {
            addCriterion("YFCPFL in", values, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflNotIn(List<Double> values) {
            addCriterion("YFCPFL not in", values, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflBetween(Double value1, Double value2) {
            addCriterion("YFCPFL between", value1, value2, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcpflNotBetween(Double value1, Double value2) {
            addCriterion("YFCPFL not between", value1, value2, "yfcpfl");
            return (Criteria) this;
        }

        public Criteria andYfcxsIsNull() {
            addCriterion("YFCXS is null");
            return (Criteria) this;
        }

        public Criteria andYfcxsIsNotNull() {
            addCriterion("YFCXS is not null");
            return (Criteria) this;
        }

        public Criteria andYfcxsEqualTo(Double value) {
            addCriterion("YFCXS =", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsNotEqualTo(Double value) {
            addCriterion("YFCXS <>", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsGreaterThan(Double value) {
            addCriterion("YFCXS >", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsGreaterThanOrEqualTo(Double value) {
            addCriterion("YFCXS >=", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsLessThan(Double value) {
            addCriterion("YFCXS <", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsLessThanOrEqualTo(Double value) {
            addCriterion("YFCXS <=", value, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsIn(List<Double> values) {
            addCriterion("YFCXS in", values, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsNotIn(List<Double> values) {
            addCriterion("YFCXS not in", values, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsBetween(Double value1, Double value2) {
            addCriterion("YFCXS between", value1, value2, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andYfcxsNotBetween(Double value1, Double value2) {
            addCriterion("YFCXS not between", value1, value2, "yfcxs");
            return (Criteria) this;
        }

        public Criteria andDyhwpflIsNull() {
            addCriterion("DYHWPFL is null");
            return (Criteria) this;
        }

        public Criteria andDyhwpflIsNotNull() {
            addCriterion("DYHWPFL is not null");
            return (Criteria) this;
        }

        public Criteria andDyhwpflEqualTo(Double value) {
            addCriterion("DYHWPFL =", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflNotEqualTo(Double value) {
            addCriterion("DYHWPFL <>", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflGreaterThan(Double value) {
            addCriterion("DYHWPFL >", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflGreaterThanOrEqualTo(Double value) {
            addCriterion("DYHWPFL >=", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflLessThan(Double value) {
            addCriterion("DYHWPFL <", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflLessThanOrEqualTo(Double value) {
            addCriterion("DYHWPFL <=", value, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflIn(List<Double> values) {
            addCriterion("DYHWPFL in", values, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflNotIn(List<Double> values) {
            addCriterion("DYHWPFL not in", values, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflBetween(Double value1, Double value2) {
            addCriterion("DYHWPFL between", value1, value2, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwpflNotBetween(Double value1, Double value2) {
            addCriterion("DYHWPFL not between", value1, value2, "dyhwpfl");
            return (Criteria) this;
        }

        public Criteria andDyhwxsIsNull() {
            addCriterion("DYHWXS is null");
            return (Criteria) this;
        }

        public Criteria andDyhwxsIsNotNull() {
            addCriterion("DYHWXS is not null");
            return (Criteria) this;
        }

        public Criteria andDyhwxsEqualTo(Double value) {
            addCriterion("DYHWXS =", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsNotEqualTo(Double value) {
            addCriterion("DYHWXS <>", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsGreaterThan(Double value) {
            addCriterion("DYHWXS >", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsGreaterThanOrEqualTo(Double value) {
            addCriterion("DYHWXS >=", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsLessThan(Double value) {
            addCriterion("DYHWXS <", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsLessThanOrEqualTo(Double value) {
            addCriterion("DYHWXS <=", value, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsIn(List<Double> values) {
            addCriterion("DYHWXS in", values, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsNotIn(List<Double> values) {
            addCriterion("DYHWXS not in", values, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsBetween(Double value1, Double value2) {
            addCriterion("DYHWXS between", value1, value2, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andDyhwxsNotBetween(Double value1, Double value2) {
            addCriterion("DYHWXS not between", value1, value2, "dyhwxs");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlIsNull() {
            addCriterion("GTFQWDQL is null");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlIsNotNull() {
            addCriterion("GTFQWDQL is not null");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlEqualTo(Double value) {
            addCriterion("GTFQWDQL =", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlNotEqualTo(Double value) {
            addCriterion("GTFQWDQL <>", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlGreaterThan(Double value) {
            addCriterion("GTFQWDQL >", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlGreaterThanOrEqualTo(Double value) {
            addCriterion("GTFQWDQL >=", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlLessThan(Double value) {
            addCriterion("GTFQWDQL <", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlLessThanOrEqualTo(Double value) {
            addCriterion("GTFQWDQL <=", value, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlIn(List<Double> values) {
            addCriterion("GTFQWDQL in", values, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlNotIn(List<Double> values) {
            addCriterion("GTFQWDQL not in", values, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlBetween(Double value1, Double value2) {
            addCriterion("GTFQWDQL between", value1, value2, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfqwdqlNotBetween(Double value1, Double value2) {
            addCriterion("GTFQWDQL not between", value1, value2, "gtfqwdql");
            return (Criteria) this;
        }

        public Criteria andGtfwxsIsNull() {
            addCriterion("GTFWXS is null");
            return (Criteria) this;
        }

        public Criteria andGtfwxsIsNotNull() {
            addCriterion("GTFWXS is not null");
            return (Criteria) this;
        }

        public Criteria andGtfwxsEqualTo(Double value) {
            addCriterion("GTFWXS =", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsNotEqualTo(Double value) {
            addCriterion("GTFWXS <>", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsGreaterThan(Double value) {
            addCriterion("GTFWXS >", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsGreaterThanOrEqualTo(Double value) {
            addCriterion("GTFWXS >=", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsLessThan(Double value) {
            addCriterion("GTFWXS <", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsLessThanOrEqualTo(Double value) {
            addCriterion("GTFWXS <=", value, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsIn(List<Double> values) {
            addCriterion("GTFWXS in", values, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsNotIn(List<Double> values) {
            addCriterion("GTFWXS not in", values, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsBetween(Double value1, Double value2) {
            addCriterion("GTFWXS between", value1, value2, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andGtfwxsNotBetween(Double value1, Double value2) {
            addCriterion("GTFWXS not between", value1, value2, "gtfwxs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsIsNull() {
            addCriterion("WRFHZS is null");
            return (Criteria) this;
        }

        public Criteria andWrfhzsIsNotNull() {
            addCriterion("WRFHZS is not null");
            return (Criteria) this;
        }

        public Criteria andWrfhzsEqualTo(Double value) {
            addCriterion("WRFHZS =", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsNotEqualTo(Double value) {
            addCriterion("WRFHZS <>", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsGreaterThan(Double value) {
            addCriterion("WRFHZS >", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsGreaterThanOrEqualTo(Double value) {
            addCriterion("WRFHZS >=", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsLessThan(Double value) {
            addCriterion("WRFHZS <", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsLessThanOrEqualTo(Double value) {
            addCriterion("WRFHZS <=", value, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsIn(List<Double> values) {
            addCriterion("WRFHZS in", values, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsNotIn(List<Double> values) {
            addCriterion("WRFHZS not in", values, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsBetween(Double value1, Double value2) {
            addCriterion("WRFHZS between", value1, value2, "wrfhzs");
            return (Criteria) this;
        }

        public Criteria andWrfhzsNotBetween(Double value1, Double value2) {
            addCriterion("WRFHZS not between", value1, value2, "wrfhzs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_wrfhzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}