package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjjczzSnei implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_snei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_snei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_snei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_snei.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ei2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_snei.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String pjjg2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_snei
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_snei.ID
     *
     * @return the value of t_hjjczz_snei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_snei.ID
     *
     * @param id the value for t_hjjczz_snei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_snei.XZQMC
     *
     * @return the value of t_hjjczz_snei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_snei.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_snei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_snei.XZQDM
     *
     * @return the value of t_hjjczz_snei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_snei.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_snei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_snei.EI2017
     *
     * @return the value of t_hjjczz_snei.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getEi2017() {
        return ei2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_snei.EI2017
     *
     * @param ei2017 the value for t_hjjczz_snei.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setEi2017(Double ei2017) {
        this.ei2017 = ei2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_snei.PJJG2017
     *
     * @return the value of t_hjjczz_snei.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getPjjg2017() {
        return pjjg2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_snei.PJJG2017
     *
     * @param pjjg2017 the value for t_hjjczz_snei.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPjjg2017(String pjjg2017) {
        this.pjjg2017 = pjjg2017;
    }
}