package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjjczzEidbpx implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.EI2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ei2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.PJJG2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String pjjg2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.PX2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer px2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double ei2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String pjjg2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.PX2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer px2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.EIBH
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double eibh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eidbpx.BHFJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String bhfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_eidbpx
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.ID
     *
     * @return the value of t_hjjczz_eidbpx.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.ID
     *
     * @param id the value for t_hjjczz_eidbpx.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.XZQMC
     *
     * @return the value of t_hjjczz_eidbpx.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_eidbpx.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.XZQDM
     *
     * @return the value of t_hjjczz_eidbpx.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_eidbpx.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.EI2016
     *
     * @return the value of t_hjjczz_eidbpx.EI2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getEi2016() {
        return ei2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.EI2016
     *
     * @param ei2016 the value for t_hjjczz_eidbpx.EI2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setEi2016(Double ei2016) {
        this.ei2016 = ei2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.PJJG2016
     *
     * @return the value of t_hjjczz_eidbpx.PJJG2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getPjjg2016() {
        return pjjg2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.PJJG2016
     *
     * @param pjjg2016 the value for t_hjjczz_eidbpx.PJJG2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPjjg2016(String pjjg2016) {
        this.pjjg2016 = pjjg2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.PX2016
     *
     * @return the value of t_hjjczz_eidbpx.PX2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getPx2016() {
        return px2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.PX2016
     *
     * @param px2016 the value for t_hjjczz_eidbpx.PX2016
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPx2016(Integer px2016) {
        this.px2016 = px2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.EI2017
     *
     * @return the value of t_hjjczz_eidbpx.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getEi2017() {
        return ei2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.EI2017
     *
     * @param ei2017 the value for t_hjjczz_eidbpx.EI2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setEi2017(Double ei2017) {
        this.ei2017 = ei2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.PJJG2017
     *
     * @return the value of t_hjjczz_eidbpx.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getPjjg2017() {
        return pjjg2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.PJJG2017
     *
     * @param pjjg2017 the value for t_hjjczz_eidbpx.PJJG2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPjjg2017(String pjjg2017) {
        this.pjjg2017 = pjjg2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.PX2017
     *
     * @return the value of t_hjjczz_eidbpx.PX2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getPx2017() {
        return px2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.PX2017
     *
     * @param px2017 the value for t_hjjczz_eidbpx.PX2017
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPx2017(Integer px2017) {
        this.px2017 = px2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.EIBH
     *
     * @return the value of t_hjjczz_eidbpx.EIBH
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getEibh() {
        return eibh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.EIBH
     *
     * @param eibh the value for t_hjjczz_eidbpx.EIBH
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setEibh(Double eibh) {
        this.eibh = eibh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eidbpx.BHFJ
     *
     * @return the value of t_hjjczz_eidbpx.BHFJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getBhfj() {
        return bhfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eidbpx.BHFJ
     *
     * @param bhfj the value for t_hjjczz_eidbpx.BHFJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setBhfj(String bhfj) {
        this.bhfj = bhfj;
    }
}