package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjjczzSthjzlei implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double swfdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double zbfgzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double swmdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double tdxpzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double wrfhzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sthjzkzsei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String pjjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double xymj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_sthjzlei
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.ID
     *
     * @return the value of t_hjjczz_sthjzlei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.ID
     *
     * @param id the value for t_hjjczz_sthjzlei.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @return the value of t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_sthjzlei.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @return the value of t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_sthjzlei.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @return the value of t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSwfdzs() {
        return swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.SWFDZS
     *
     * @param swfdzs the value for t_hjjczz_sthjzlei.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSwfdzs(Double swfdzs) {
        this.swfdzs = swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @return the value of t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getZbfgzs() {
        return zbfgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.ZBFGZS
     *
     * @param zbfgzs the value for t_hjjczz_sthjzlei.ZBFGZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setZbfgzs(Double zbfgzs) {
        this.zbfgzs = zbfgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @return the value of t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSwmdzs() {
        return swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.SWMDZS
     *
     * @param swmdzs the value for t_hjjczz_sthjzlei.SWMDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSwmdzs(Double swmdzs) {
        this.swmdzs = swmdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @return the value of t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getTdxpzs() {
        return tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.TDXPZS
     *
     * @param tdxpzs the value for t_hjjczz_sthjzlei.TDXPZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setTdxpzs(Double tdxpzs) {
        this.tdxpzs = tdxpzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @return the value of t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getWrfhzs() {
        return wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.WRFHZS
     *
     * @param wrfhzs the value for t_hjjczz_sthjzlei.WRFHZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setWrfhzs(Double wrfhzs) {
        this.wrfhzs = wrfhzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @return the value of t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSthjzkzsei() {
        return sthjzkzsei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @param sthjzkzsei the value for t_hjjczz_sthjzlei.STHJZKZSEI
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSthjzkzsei(Double sthjzkzsei) {
        this.sthjzkzsei = sthjzkzsei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.PJJG
     *
     * @return the value of t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getPjjg() {
        return pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.PJJG
     *
     * @param pjjg the value for t_hjjczz_sthjzlei.PJJG
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setPjjg(String pjjg) {
        this.pjjg = pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @return the value of t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getXymj() {
        return xymj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_sthjzlei.XYMJ
     *
     * @param xymj the value for t_hjjczz_sthjzlei.XYMJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXymj(Double xymj) {
        this.xymj = xymj;
    }
}