package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjjczzSwfdzs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String xzqdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sjzlz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sjgyhxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double sjzlzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double swdyxzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double swfdzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swfdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.ID
     *
     * @return the value of t_hjjczz_swfdzs.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.ID
     *
     * @param id the value for t_hjjczz_swfdzs.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.XZQMC
     *
     * @return the value of t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.XZQMC
     *
     * @param xzqmc the value for t_hjjczz_swfdzs.XZQMC
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.XZQDM
     *
     * @return the value of t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getXzqdm() {
        return xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.XZQDM
     *
     * @param xzqdm the value for t_hjjczz_swfdzs.XZQDM
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @return the value of t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSjzlz() {
        return sjzlz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJZLZ
     *
     * @param sjzlz the value for t_hjjczz_swfdzs.SJZLZ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSjzlz(Double sjzlz) {
        this.sjzlz = sjzlz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @return the value of t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSjgyhxs() {
        return sjgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJGYHXS
     *
     * @param sjgyhxs the value for t_hjjczz_swfdzs.SJGYHXS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSjgyhxs(Double sjgyhxs) {
        this.sjgyhxs = sjgyhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @return the value of t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSjzlzs() {
        return sjzlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SJZLZS
     *
     * @param sjzlzs the value for t_hjjczz_swfdzs.SJZLZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSjzlzs(Double sjzlzs) {
        this.sjzlzs = sjzlzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @return the value of t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSwdyxzs() {
        return swdyxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SWDYXZS
     *
     * @param swdyxzs the value for t_hjjczz_swfdzs.SWDYXZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSwdyxzs(Double swdyxzs) {
        this.swdyxzs = swdyxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @return the value of t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getSwfdzs() {
        return swfdzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_swfdzs.SWFDZS
     *
     * @param swfdzs the value for t_hjjczz_swfdzs.SWFDZS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setSwfdzs(Double swfdzs) {
        this.swfdzs = swfdzs;
    }
}