package com.fiprs.springbootdemo.entity;

import java.io.Serializable;

public class THjjczzEihz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.LB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.FW
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String fw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.GS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Integer gs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private Double mj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.GSBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String gsbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hjjczz_eihz.MJBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private String mjbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_eihz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.ID
     *
     * @return the value of t_hjjczz_eihz.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.ID
     *
     * @param id the value for t_hjjczz_eihz.ID
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.LB
     *
     * @return the value of t_hjjczz_eihz.LB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.LB
     *
     * @param lb the value for t_hjjczz_eihz.LB
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setLb(String lb) {
        this.lb = lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.FW
     *
     * @return the value of t_hjjczz_eihz.FW
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getFw() {
        return fw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.FW
     *
     * @param fw the value for t_hjjczz_eihz.FW
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setFw(String fw) {
        this.fw = fw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.GS
     *
     * @return the value of t_hjjczz_eihz.GS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Integer getGs() {
        return gs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.GS
     *
     * @param gs the value for t_hjjczz_eihz.GS
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGs(Integer gs) {
        this.gs = gs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.MJ
     *
     * @return the value of t_hjjczz_eihz.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Double getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.MJ
     *
     * @param mj the value for t_hjjczz_eihz.MJ
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setMj(Double mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.GSBL
     *
     * @return the value of t_hjjczz_eihz.GSBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getGsbl() {
        return gsbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.GSBL
     *
     * @param gsbl the value for t_hjjczz_eihz.GSBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setGsbl(String gsbl) {
        this.gsbl = gsbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hjjczz_eihz.MJBL
     *
     * @return the value of t_hjjczz_eihz.MJBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getMjbl() {
        return mjbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hjjczz_eihz.MJBL
     *
     * @param mjbl the value for t_hjjczz_eihz.MJBL
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setMjbl(String mjbl) {
        this.mjbl = mjbl;
    }
}