package com.fiprs.springbootdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class THjjczzSwmdzsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public THjjczzSwmdzsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNull() {
            addCriterion("XZQMC is null");
            return (Criteria) this;
        }

        public Criteria andXzqmcIsNotNull() {
            addCriterion("XZQMC is not null");
            return (Criteria) this;
        }

        public Criteria andXzqmcEqualTo(String value) {
            addCriterion("XZQMC =", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotEqualTo(String value) {
            addCriterion("XZQMC <>", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThan(String value) {
            addCriterion("XZQMC >", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcGreaterThanOrEqualTo(String value) {
            addCriterion("XZQMC >=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThan(String value) {
            addCriterion("XZQMC <", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLessThanOrEqualTo(String value) {
            addCriterion("XZQMC <=", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcLike(String value) {
            addCriterion("XZQMC like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotLike(String value) {
            addCriterion("XZQMC not like", value, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcIn(List<String> values) {
            addCriterion("XZQMC in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotIn(List<String> values) {
            addCriterion("XZQMC not in", values, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcBetween(String value1, String value2) {
            addCriterion("XZQMC between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqmcNotBetween(String value1, String value2) {
            addCriterion("XZQMC not between", value1, value2, "xzqmc");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNull() {
            addCriterion("XZQDM is null");
            return (Criteria) this;
        }

        public Criteria andXzqdmIsNotNull() {
            addCriterion("XZQDM is not null");
            return (Criteria) this;
        }

        public Criteria andXzqdmEqualTo(String value) {
            addCriterion("XZQDM =", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotEqualTo(String value) {
            addCriterion("XZQDM <>", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThan(String value) {
            addCriterion("XZQDM >", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmGreaterThanOrEqualTo(String value) {
            addCriterion("XZQDM >=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThan(String value) {
            addCriterion("XZQDM <", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLessThanOrEqualTo(String value) {
            addCriterion("XZQDM <=", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmLike(String value) {
            addCriterion("XZQDM like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotLike(String value) {
            addCriterion("XZQDM not like", value, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmIn(List<String> values) {
            addCriterion("XZQDM in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotIn(List<String> values) {
            addCriterion("XZQDM not in", values, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmBetween(String value1, String value2) {
            addCriterion("XZQDM between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andXzqdmNotBetween(String value1, String value2) {
            addCriterion("XZQDM not between", value1, value2, "xzqdm");
            return (Criteria) this;
        }

        public Criteria andMjIsNull() {
            addCriterion("MJ is null");
            return (Criteria) this;
        }

        public Criteria andMjIsNotNull() {
            addCriterion("MJ is not null");
            return (Criteria) this;
        }

        public Criteria andMjEqualTo(Double value) {
            addCriterion("MJ =", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotEqualTo(Double value) {
            addCriterion("MJ <>", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThan(Double value) {
            addCriterion("MJ >", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThanOrEqualTo(Double value) {
            addCriterion("MJ >=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThan(Double value) {
            addCriterion("MJ <", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThanOrEqualTo(Double value) {
            addCriterion("MJ <=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjIn(List<Double> values) {
            addCriterion("MJ in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotIn(List<Double> values) {
            addCriterion("MJ not in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjBetween(Double value1, Double value2) {
            addCriterion("MJ between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotBetween(Double value1, Double value2) {
            addCriterion("MJ not between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andHlcdIsNull() {
            addCriterion("HLCD is null");
            return (Criteria) this;
        }

        public Criteria andHlcdIsNotNull() {
            addCriterion("HLCD is not null");
            return (Criteria) this;
        }

        public Criteria andHlcdEqualTo(Double value) {
            addCriterion("HLCD =", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdNotEqualTo(Double value) {
            addCriterion("HLCD <>", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdGreaterThan(Double value) {
            addCriterion("HLCD >", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdGreaterThanOrEqualTo(Double value) {
            addCriterion("HLCD >=", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdLessThan(Double value) {
            addCriterion("HLCD <", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdLessThanOrEqualTo(Double value) {
            addCriterion("HLCD <=", value, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdIn(List<Double> values) {
            addCriterion("HLCD in", values, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdNotIn(List<Double> values) {
            addCriterion("HLCD not in", values, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdBetween(Double value1, Double value2) {
            addCriterion("HLCD between", value1, value2, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlcdNotBetween(Double value1, Double value2) {
            addCriterion("HLCD not between", value1, value2, "hlcd");
            return (Criteria) this;
        }

        public Criteria andHlxsIsNull() {
            addCriterion("HLXS is null");
            return (Criteria) this;
        }

        public Criteria andHlxsIsNotNull() {
            addCriterion("HLXS is not null");
            return (Criteria) this;
        }

        public Criteria andHlxsEqualTo(Double value) {
            addCriterion("HLXS =", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsNotEqualTo(Double value) {
            addCriterion("HLXS <>", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsGreaterThan(Double value) {
            addCriterion("HLXS >", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsGreaterThanOrEqualTo(Double value) {
            addCriterion("HLXS >=", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsLessThan(Double value) {
            addCriterion("HLXS <", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsLessThanOrEqualTo(Double value) {
            addCriterion("HLXS <=", value, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsIn(List<Double> values) {
            addCriterion("HLXS in", values, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsNotIn(List<Double> values) {
            addCriterion("HLXS not in", values, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsBetween(Double value1, Double value2) {
            addCriterion("HLXS between", value1, value2, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlxsNotBetween(Double value1, Double value2) {
            addCriterion("HLXS not between", value1, value2, "hlxs");
            return (Criteria) this;
        }

        public Criteria andHlzsIsNull() {
            addCriterion("HLZS is null");
            return (Criteria) this;
        }

        public Criteria andHlzsIsNotNull() {
            addCriterion("HLZS is not null");
            return (Criteria) this;
        }

        public Criteria andHlzsEqualTo(Double value) {
            addCriterion("HLZS =", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsNotEqualTo(Double value) {
            addCriterion("HLZS <>", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsGreaterThan(Double value) {
            addCriterion("HLZS >", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsGreaterThanOrEqualTo(Double value) {
            addCriterion("HLZS >=", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsLessThan(Double value) {
            addCriterion("HLZS <", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsLessThanOrEqualTo(Double value) {
            addCriterion("HLZS <=", value, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsIn(List<Double> values) {
            addCriterion("HLZS in", values, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsNotIn(List<Double> values) {
            addCriterion("HLZS not in", values, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsBetween(Double value1, Double value2) {
            addCriterion("HLZS between", value1, value2, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHlzsNotBetween(Double value1, Double value2) {
            addCriterion("HLZS not between", value1, value2, "hlzs");
            return (Criteria) this;
        }

        public Criteria andHkmjIsNull() {
            addCriterion("HKMJ is null");
            return (Criteria) this;
        }

        public Criteria andHkmjIsNotNull() {
            addCriterion("HKMJ is not null");
            return (Criteria) this;
        }

        public Criteria andHkmjEqualTo(Double value) {
            addCriterion("HKMJ =", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjNotEqualTo(Double value) {
            addCriterion("HKMJ <>", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjGreaterThan(Double value) {
            addCriterion("HKMJ >", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjGreaterThanOrEqualTo(Double value) {
            addCriterion("HKMJ >=", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjLessThan(Double value) {
            addCriterion("HKMJ <", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjLessThanOrEqualTo(Double value) {
            addCriterion("HKMJ <=", value, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjIn(List<Double> values) {
            addCriterion("HKMJ in", values, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjNotIn(List<Double> values) {
            addCriterion("HKMJ not in", values, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjBetween(Double value1, Double value2) {
            addCriterion("HKMJ between", value1, value2, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkmjNotBetween(Double value1, Double value2) {
            addCriterion("HKMJ not between", value1, value2, "hkmj");
            return (Criteria) this;
        }

        public Criteria andHkxsIsNull() {
            addCriterion("HKXS is null");
            return (Criteria) this;
        }

        public Criteria andHkxsIsNotNull() {
            addCriterion("HKXS is not null");
            return (Criteria) this;
        }

        public Criteria andHkxsEqualTo(Double value) {
            addCriterion("HKXS =", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsNotEqualTo(Double value) {
            addCriterion("HKXS <>", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsGreaterThan(Double value) {
            addCriterion("HKXS >", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsGreaterThanOrEqualTo(Double value) {
            addCriterion("HKXS >=", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsLessThan(Double value) {
            addCriterion("HKXS <", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsLessThanOrEqualTo(Double value) {
            addCriterion("HKXS <=", value, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsIn(List<Double> values) {
            addCriterion("HKXS in", values, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsNotIn(List<Double> values) {
            addCriterion("HKXS not in", values, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsBetween(Double value1, Double value2) {
            addCriterion("HKXS between", value1, value2, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkxsNotBetween(Double value1, Double value2) {
            addCriterion("HKXS not between", value1, value2, "hkxs");
            return (Criteria) this;
        }

        public Criteria andHkzsIsNull() {
            addCriterion("HKZS is null");
            return (Criteria) this;
        }

        public Criteria andHkzsIsNotNull() {
            addCriterion("HKZS is not null");
            return (Criteria) this;
        }

        public Criteria andHkzsEqualTo(Double value) {
            addCriterion("HKZS =", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsNotEqualTo(Double value) {
            addCriterion("HKZS <>", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsGreaterThan(Double value) {
            addCriterion("HKZS >", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsGreaterThanOrEqualTo(Double value) {
            addCriterion("HKZS >=", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsLessThan(Double value) {
            addCriterion("HKZS <", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsLessThanOrEqualTo(Double value) {
            addCriterion("HKZS <=", value, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsIn(List<Double> values) {
            addCriterion("HKZS in", values, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsNotIn(List<Double> values) {
            addCriterion("HKZS not in", values, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsBetween(Double value1, Double value2) {
            addCriterion("HKZS between", value1, value2, "hkzs");
            return (Criteria) this;
        }

        public Criteria andHkzsNotBetween(Double value1, Double value2) {
            addCriterion("HKZS not between", value1, value2, "hkzs");
            return (Criteria) this;
        }

        public Criteria andSzylIsNull() {
            addCriterion("SZYL is null");
            return (Criteria) this;
        }

        public Criteria andSzylIsNotNull() {
            addCriterion("SZYL is not null");
            return (Criteria) this;
        }

        public Criteria andSzylEqualTo(Double value) {
            addCriterion("SZYL =", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylNotEqualTo(Double value) {
            addCriterion("SZYL <>", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylGreaterThan(Double value) {
            addCriterion("SZYL >", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylGreaterThanOrEqualTo(Double value) {
            addCriterion("SZYL >=", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylLessThan(Double value) {
            addCriterion("SZYL <", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylLessThanOrEqualTo(Double value) {
            addCriterion("SZYL <=", value, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylIn(List<Double> values) {
            addCriterion("SZYL in", values, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylNotIn(List<Double> values) {
            addCriterion("SZYL not in", values, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylBetween(Double value1, Double value2) {
            addCriterion("SZYL between", value1, value2, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzylNotBetween(Double value1, Double value2) {
            addCriterion("SZYL not between", value1, value2, "szyl");
            return (Criteria) this;
        }

        public Criteria andSzyxsIsNull() {
            addCriterion("SZYXS is null");
            return (Criteria) this;
        }

        public Criteria andSzyxsIsNotNull() {
            addCriterion("SZYXS is not null");
            return (Criteria) this;
        }

        public Criteria andSzyxsEqualTo(Double value) {
            addCriterion("SZYXS =", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsNotEqualTo(Double value) {
            addCriterion("SZYXS <>", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsGreaterThan(Double value) {
            addCriterion("SZYXS >", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsGreaterThanOrEqualTo(Double value) {
            addCriterion("SZYXS >=", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsLessThan(Double value) {
            addCriterion("SZYXS <", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsLessThanOrEqualTo(Double value) {
            addCriterion("SZYXS <=", value, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsIn(List<Double> values) {
            addCriterion("SZYXS in", values, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsNotIn(List<Double> values) {
            addCriterion("SZYXS not in", values, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsBetween(Double value1, Double value2) {
            addCriterion("SZYXS between", value1, value2, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyxsNotBetween(Double value1, Double value2) {
            addCriterion("SZYXS not between", value1, value2, "szyxs");
            return (Criteria) this;
        }

        public Criteria andSzyzsIsNull() {
            addCriterion("SZYZS is null");
            return (Criteria) this;
        }

        public Criteria andSzyzsIsNotNull() {
            addCriterion("SZYZS is not null");
            return (Criteria) this;
        }

        public Criteria andSzyzsEqualTo(Double value) {
            addCriterion("SZYZS =", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsNotEqualTo(Double value) {
            addCriterion("SZYZS <>", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsGreaterThan(Double value) {
            addCriterion("SZYZS >", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsGreaterThanOrEqualTo(Double value) {
            addCriterion("SZYZS >=", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsLessThan(Double value) {
            addCriterion("SZYZS <", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsLessThanOrEqualTo(Double value) {
            addCriterion("SZYZS <=", value, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsIn(List<Double> values) {
            addCriterion("SZYZS in", values, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsNotIn(List<Double> values) {
            addCriterion("SZYZS not in", values, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsBetween(Double value1, Double value2) {
            addCriterion("SZYZS between", value1, value2, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSzyzsNotBetween(Double value1, Double value2) {
            addCriterion("SZYZS not between", value1, value2, "szyzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsIsNull() {
            addCriterion("SWMDZS is null");
            return (Criteria) this;
        }

        public Criteria andSwmdzsIsNotNull() {
            addCriterion("SWMDZS is not null");
            return (Criteria) this;
        }

        public Criteria andSwmdzsEqualTo(Double value) {
            addCriterion("SWMDZS =", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsNotEqualTo(Double value) {
            addCriterion("SWMDZS <>", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsGreaterThan(Double value) {
            addCriterion("SWMDZS >", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsGreaterThanOrEqualTo(Double value) {
            addCriterion("SWMDZS >=", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsLessThan(Double value) {
            addCriterion("SWMDZS <", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsLessThanOrEqualTo(Double value) {
            addCriterion("SWMDZS <=", value, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsIn(List<Double> values) {
            addCriterion("SWMDZS in", values, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsNotIn(List<Double> values) {
            addCriterion("SWMDZS not in", values, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsBetween(Double value1, Double value2) {
            addCriterion("SWMDZS between", value1, value2, "swmdzs");
            return (Criteria) this;
        }

        public Criteria andSwmdzsNotBetween(Double value1, Double value2) {
            addCriterion("SWMDZS not between", value1, value2, "swmdzs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_swmdzs
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}