package com.fiprs.springbootdemo.entity;

import java.util.ArrayList;
import java.util.List;

public class THjjczzGdphzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public THjjczzGdphzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStlb2016IsNull() {
            addCriterion("STLB2016 is null");
            return (Criteria) this;
        }

        public Criteria andStlb2016IsNotNull() {
            addCriterion("STLB2016 is not null");
            return (Criteria) this;
        }

        public Criteria andStlb2016EqualTo(String value) {
            addCriterion("STLB2016 =", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016NotEqualTo(String value) {
            addCriterion("STLB2016 <>", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016GreaterThan(String value) {
            addCriterion("STLB2016 >", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016GreaterThanOrEqualTo(String value) {
            addCriterion("STLB2016 >=", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016LessThan(String value) {
            addCriterion("STLB2016 <", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016LessThanOrEqualTo(String value) {
            addCriterion("STLB2016 <=", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016Like(String value) {
            addCriterion("STLB2016 like", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016NotLike(String value) {
            addCriterion("STLB2016 not like", value, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016In(List<String> values) {
            addCriterion("STLB2016 in", values, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016NotIn(List<String> values) {
            addCriterion("STLB2016 not in", values, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016Between(String value1, String value2) {
            addCriterion("STLB2016 between", value1, value2, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andStlb2016NotBetween(String value1, String value2) {
            addCriterion("STLB2016 not between", value1, value2, "stlb2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016IsNull() {
            addCriterion("GDP2016 is null");
            return (Criteria) this;
        }

        public Criteria andGdp2016IsNotNull() {
            addCriterion("GDP2016 is not null");
            return (Criteria) this;
        }

        public Criteria andGdp2016EqualTo(Double value) {
            addCriterion("GDP2016 =", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016NotEqualTo(Double value) {
            addCriterion("GDP2016 <>", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016GreaterThan(Double value) {
            addCriterion("GDP2016 >", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016GreaterThanOrEqualTo(Double value) {
            addCriterion("GDP2016 >=", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016LessThan(Double value) {
            addCriterion("GDP2016 <", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016LessThanOrEqualTo(Double value) {
            addCriterion("GDP2016 <=", value, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016In(List<Double> values) {
            addCriterion("GDP2016 in", values, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016NotIn(List<Double> values) {
            addCriterion("GDP2016 not in", values, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016Between(Double value1, Double value2) {
            addCriterion("GDP2016 between", value1, value2, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andGdp2016NotBetween(Double value1, Double value2) {
            addCriterion("GDP2016 not between", value1, value2, "gdp2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016IsNull() {
            addCriterion("ZQSGDPBL2016 is null");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016IsNotNull() {
            addCriterion("ZQSGDPBL2016 is not null");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016EqualTo(String value) {
            addCriterion("ZQSGDPBL2016 =", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016NotEqualTo(String value) {
            addCriterion("ZQSGDPBL2016 <>", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016GreaterThan(String value) {
            addCriterion("ZQSGDPBL2016 >", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016GreaterThanOrEqualTo(String value) {
            addCriterion("ZQSGDPBL2016 >=", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016LessThan(String value) {
            addCriterion("ZQSGDPBL2016 <", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016LessThanOrEqualTo(String value) {
            addCriterion("ZQSGDPBL2016 <=", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016Like(String value) {
            addCriterion("ZQSGDPBL2016 like", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016NotLike(String value) {
            addCriterion("ZQSGDPBL2016 not like", value, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016In(List<String> values) {
            addCriterion("ZQSGDPBL2016 in", values, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016NotIn(List<String> values) {
            addCriterion("ZQSGDPBL2016 not in", values, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016Between(String value1, String value2) {
            addCriterion("ZQSGDPBL2016 between", value1, value2, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2016NotBetween(String value1, String value2) {
            addCriterion("ZQSGDPBL2016 not between", value1, value2, "zqsgdpbl2016");
            return (Criteria) this;
        }

        public Criteria andStlb2017IsNull() {
            addCriterion("STLB2017 is null");
            return (Criteria) this;
        }

        public Criteria andStlb2017IsNotNull() {
            addCriterion("STLB2017 is not null");
            return (Criteria) this;
        }

        public Criteria andStlb2017EqualTo(String value) {
            addCriterion("STLB2017 =", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017NotEqualTo(String value) {
            addCriterion("STLB2017 <>", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017GreaterThan(String value) {
            addCriterion("STLB2017 >", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017GreaterThanOrEqualTo(String value) {
            addCriterion("STLB2017 >=", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017LessThan(String value) {
            addCriterion("STLB2017 <", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017LessThanOrEqualTo(String value) {
            addCriterion("STLB2017 <=", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017Like(String value) {
            addCriterion("STLB2017 like", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017NotLike(String value) {
            addCriterion("STLB2017 not like", value, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017In(List<String> values) {
            addCriterion("STLB2017 in", values, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017NotIn(List<String> values) {
            addCriterion("STLB2017 not in", values, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017Between(String value1, String value2) {
            addCriterion("STLB2017 between", value1, value2, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andStlb2017NotBetween(String value1, String value2) {
            addCriterion("STLB2017 not between", value1, value2, "stlb2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017IsNull() {
            addCriterion("GDP2017 is null");
            return (Criteria) this;
        }

        public Criteria andGdp2017IsNotNull() {
            addCriterion("GDP2017 is not null");
            return (Criteria) this;
        }

        public Criteria andGdp2017EqualTo(Double value) {
            addCriterion("GDP2017 =", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017NotEqualTo(Double value) {
            addCriterion("GDP2017 <>", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017GreaterThan(Double value) {
            addCriterion("GDP2017 >", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017GreaterThanOrEqualTo(Double value) {
            addCriterion("GDP2017 >=", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017LessThan(Double value) {
            addCriterion("GDP2017 <", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017LessThanOrEqualTo(Double value) {
            addCriterion("GDP2017 <=", value, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017In(List<Double> values) {
            addCriterion("GDP2017 in", values, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017NotIn(List<Double> values) {
            addCriterion("GDP2017 not in", values, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017Between(Double value1, Double value2) {
            addCriterion("GDP2017 between", value1, value2, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andGdp2017NotBetween(Double value1, Double value2) {
            addCriterion("GDP2017 not between", value1, value2, "gdp2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017IsNull() {
            addCriterion("ZQSGDPBL2017 is null");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017IsNotNull() {
            addCriterion("ZQSGDPBL2017 is not null");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017EqualTo(String value) {
            addCriterion("ZQSGDPBL2017 =", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017NotEqualTo(String value) {
            addCriterion("ZQSGDPBL2017 <>", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017GreaterThan(String value) {
            addCriterion("ZQSGDPBL2017 >", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017GreaterThanOrEqualTo(String value) {
            addCriterion("ZQSGDPBL2017 >=", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017LessThan(String value) {
            addCriterion("ZQSGDPBL2017 <", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017LessThanOrEqualTo(String value) {
            addCriterion("ZQSGDPBL2017 <=", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017Like(String value) {
            addCriterion("ZQSGDPBL2017 like", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017NotLike(String value) {
            addCriterion("ZQSGDPBL2017 not like", value, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017In(List<String> values) {
            addCriterion("ZQSGDPBL2017 in", values, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017NotIn(List<String> values) {
            addCriterion("ZQSGDPBL2017 not in", values, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017Between(String value1, String value2) {
            addCriterion("ZQSGDPBL2017 between", value1, value2, "zqsgdpbl2017");
            return (Criteria) this;
        }

        public Criteria andZqsgdpbl2017NotBetween(String value1, String value2) {
            addCriterion("ZQSGDPBL2017 not between", value1, value2, "zqsgdpbl2017");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hjjczz_gdphz
     *
     * @mbggenerated Wed Nov 04 15:15:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}